# ================================
# BACKEND - NEXT.JS + PRISMA
# ================================
FROM node:20-alpine AS builder

WORKDIR /app

# Copiar apenas arquivos de dependência primeiro (melhora cache)
COPY package*.json ./

RUN npm install

# Copiar todo o restante do projeto
COPY . .

# Gerar Prisma Client e buildar o projeto Next.js
RUN npx prisma generate
RUN npm run build

# ================================
# STAGE FINAL (somente arquivos necessários)
# ================================
FROM node:20-alpine

WORKDIR /app

# Copiar apenas o resultado do build e dependências
COPY --from=builder /app/package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/.next .next
COPY --from=builder /app/public ./public
COPY --from=builder /app/prisma ./prisma

EXPOSE 3000

RUN apk add --no-cache netcat-openbsd


COPY wait-for-db.sh ./wait-for-db.sh
RUN chmod +x ./wait-for-db.sh

CMD ["sh", "wait-for-db.sh", "sh", "-c", "npx prisma migrate deploy && npm run start"]